Areas/Admin/ViewComponents/SidebarMenuViewComponent.cs
using DotNetCoreWeb.AdminLTE.ProjectTemplates.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreWeb.AdminLTE.ProjectTemplates.Areas.Admin.ViewComponents
{
    public class SidebarMenuViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<SidebarMenuViewModel> model = new List<SidebarMenuViewModel>();

            model.AddRange(GetExamplesMenu());
            model.AddRange(GetMiscellaneousMenu());
            model.AddRange(GetLabelMenu());


            return View(model);
        }
        private IList<SidebarMenuViewModel> GetExamplesMenu()
        {
            IList<SidebarMenuViewModel> result = new List<SidebarMenuViewModel>();
            result.Add(new SidebarMenuViewModel() { IsHeader = true, Title = "EXAMPLES" });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Calendar",
                Class = "nav-icon far fa-calendar-alt",
                Url = new DataUrl("Index", "Home", "Admin")
            });

            result.Add(new SidebarMenuViewModel()
            {
                Title = "Gallery",
                Class = "nav-icon far fa-image",
                Url = new DataUrl("Index", "Home", "Admin")
            });

            result.Add(new SidebarMenuViewModel()
            {
                Title = "Kanban Board",
                Class = "nav-icon fas fa-columns",
                Url = new DataUrl("Index", "Home", "Admin")
            });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Mailbox",
                Class = "nav-icon far fa-envelope",
                //Url = new DataUrl("Index", "Home", "Admin")
                Child = new List<SidebarMenuViewModel>()
                {
                    new SidebarMenuViewModel()
                    {
                        Title = "Inbox",
                        Class = "far fa-circle nav-icon",
                        Url = new DataUrl("Index", "Home", "Admin")
                    },
                    new SidebarMenuViewModel()
                    {
                        Title = "Compose",
                        Class = "far fa-circle nav-icon",
                        Url = new DataUrl("Index", "Home", "Admin")
                    },
                    new SidebarMenuViewModel()
                    {
                        Title = "Read",
                        Class = "far fa-circle nav-icon",
                        Url = new DataUrl("Index", "Home", "Admin")
                    }
                }
            });

            result.Add(new SidebarMenuViewModel()
            {
                Title = "Pages",
                Class = "nav-icon fas fa-book",
                //Url = new DataUrl("Index", "Home", "Admin")
                Child = new List<SidebarMenuViewModel>()
                {
                    new SidebarMenuViewModel()
                    {
                        Title = "Invoice",
                        Class = "far fa-circle nav-icon",
                        Url = new DataUrl("Index", "Home", "Admin")
                    },
                    new SidebarMenuViewModel()
                    {
                        Title = "Profile",
                        Class = "far fa-circle nav-icon",
                        Url = new DataUrl("Index", "Home", "Admin")
                    },
                    new SidebarMenuViewModel()
                    {
                        Title = "E-commerce",
                        Class = "far fa-circle nav-icon",
                        Url = new DataUrl("Index", "Home", "Admin")
                    }
                }
            });

            return result;
        }
        private IList<SidebarMenuViewModel> GetMiscellaneousMenu()
        {
            IList<SidebarMenuViewModel> result = new List<SidebarMenuViewModel>();
            result.Add(new SidebarMenuViewModel() { IsHeader = true, Title = "MISCELLANEOUS" });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Tabbed IFrame Plugin",
                Class = "nav-icon fas fa-ellipsis-h",
                Url = new DataUrl("Index", "Home", "Admin")
            });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Documentation",
                Class = "nav-icon fas fa-file",
                //Url = new DataUrl("Index", "Home", "Admin")
                Url = new DataUrl("https://adminlte.io/docs/3.1/")
            });
            return result;
        }
        private IList<SidebarMenuViewModel> GetLabelMenu()
        {
            IList<SidebarMenuViewModel> result = new List<SidebarMenuViewModel>();
            result.Add(new SidebarMenuViewModel() { IsHeader = true, Title = "LABELS" });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Important",
                Class = "nav-icon far fa-circle text-danger",
                Url = new DataUrl("Index", "Home", "Admin")
            });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Warning",
                Class = "nav-icon far fa-circle text-warning",
                Url = new DataUrl("Index", "Home", "Admin")
            });
            result.Add(new SidebarMenuViewModel()
            {
                Title = "Informational",
                Class = "nav-icon far fa-circle text-info",
                Url = new DataUrl("Index", "Home", "Admin")
            });
            return result;
        }
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - DotNetCoreWeb.AdminLTE.ProjectTemplates</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/fontawesome-free/css/all.min.css">
    <!-- Admin Lte -->
    <link rel="stylesheet" href="~/css/adminlte.css"/>
    <!-- Build in -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/DotNetCoreWeb.AdminLTE.ProjectTemplates.styles.css" asp-append-version="true"/>

    @await RenderSectionAsync("Css", required: false)
</head>
<body class="sidebar-mini layout-fixed control-sidebar-slide-open layout-footer-fixed layout-navbar-fixed">


<div class="wrapper">

<!-- Preloader -->
<div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="~/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
</div>

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button">
                <i class="fas fa-bars"></i>
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger">
                                    <i class="fas fa-star"></i>
                                </span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted">
                                    <i class="fas fa-star"></i>
                                </span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning">
                                    <i class="fas fa-star"></i>
                                </span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">

    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="~/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        @await Component.InvokeAsync("SidebarUserPanel")

        <!-- SidebarSearch Form -->
        @*@await Component.InvokeAsync("SidebarSearchForm")*@
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        @await Component.InvokeAsync("SidebarMenu")

    </div>
    <!-- /.sidebar -->
</aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
       @RenderBody()
  </div>
<!-- /.content-wrapper -->


<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.2.0
    </div>
</footer>


</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/adminlte.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>